version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo $CODEBUILD_SOURCE_REPO_URL
      - echo $CODEBUILD_GIT_BRANCH
      - echo $CODEBUILD_SOURCE_REPO_URL | rev | cut -d '/' -f 1 | rev > details.txt
      - echo $CODEBUILD_GIT_BRANCH >> details.txt
      - cat details.txt
