version: 0.2

env:
  git-credential-helper: yes
  exported-variables:
    - BUILD_OUTPUT
phases:
  install:
    #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
    #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
    runtime-versions:
      nodejs: 10
      # name: version
    #commands:
      # - command
      # - command
  pre_build:
    commands:
      - ls -lt
      - cat README.md
  build:
    commands:
      - if [[ $(git log -n1 --since="2 minutes ago") ]]; then BUILD_OUTPUT=$(basename "$PWD"); fi
      - echo $BUILD_OUTPUT
      - cd $CODEBUILD_SRC_DIR_Source2
      - if [[ $(git log -n1 --since="2 minutes ago") ]]; then BUILD_OUTPUT=$(basename "$PWD"); fi
      - echo $BUILD_OUTPUT
