version: 0.2

env:
  git-credential-helper: yes
  exported-variables:
    - BUILD_OUTPUT
phases:
  install:
    #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
    #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
    runtime-versions:
      nodejs: 10
      # name: version
    #commands:
      # - command
      # - command
  pre_build:
    commands:
      - ls -lt
      - cat README.md
  build:
    commands:
      - git log | head -5 | tail -1|grep -q "commited" && BUILD_OUTPUT=$(basename "$PWD") || true
      #- if[[ $? == 0 ]]; then BUILD_OUTPUT=$(basename "$PWD"); fi
      - echo $BUILD_OUTPUT
      - git status
      - ls
      - git archive --format=zip HEAD > application.zip
      - pwd
      - cd $CODEBUILD_SRC_DIR_Source2
      - pwd
      - git log | head -5 | tail -1|grep -q "commited" && BUILD_OUTPUT=$(basename "$PWD") || true
      #- if [[ $? == 0 ]]; then BUILD_OUTPUT=$(basename "$PWD"); fi
  #post_build:
    #commands:
      # - command
      # - command
artifacts:
  files:
    - application.zip
    # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths


